### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by MasterKN48** [MasterKN48/MERN-Stack-Login-Methods#1]
Want to prepare good documentation for this project, where i want to implement various login methods with nodejs,reactjs

**Comment by djiwandou** [comment]
Hi @MasterKN48 I am still a newbie, how can I contribute? any readme or guide? 🙏

**Comment by MasterKN48** [comment]
You can create a good documentation about this project.
Documentation includes 

1. Project heading , demo URL (will update later),usage,how to install.
2. Information about Server side directory structure.
3. Client side directory structure.
4. Checklist of  login method provider (i.e. github,google,twitter,etc)

If You can do that any of it go ahead.

**Comment by djiwandou** [comment]
Ok thanks @MasterKN48 I'll try my best 👍
