### ISSUE TITLE
React App for login/signup

### ISSUE THREAD

**Issue by MasterKN48** [MasterKN48/MERN-Stack-Login-Methods#10]
Want to create react app with login/signup using nodejs endpoint already created in this repository.

client side login app for log-in using current available login strategy Google, Facebook, Twitter, Reddit, jwt in this repository.
"docs-for-api.md" has api endpoints that may require at client side.
Try to make by using hooks,functional component instead of class based component

**Comment by sudharsangs** [comment]
I will take up this issue

**Comment by MasterKN48** [comment]
Sure @sudharsangs  do it.

**Comment by mashiromashi** [comment]
Have you decided the web design yet ? or should I just come up on my own ?

**Comment by MasterKN48** [comment]
Go with your own design
